export interface MappingEntry {
  localized: string;
  [key: string]: string;
}

const itemTypeLocalizations: Record<string, Record<string, string>> = {
  "fr-FR": {
    attachment: "Piece jointe",
    book: "Livre",
    computerProgram: "Logiciel",
    journalArticle: "Article de revue",
    note: "Note",
  },
};

const labelFromCamelCase = (value: string): string =>
  value
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/^./, (letter) => letter.toUpperCase());

const itemTypeNames = [
  "artwork",
  "attachment",
  "audioRecording",
  "bill",
  "blogPost",
  "book",
  "bookSection",
  "case",
  "computerProgram",
  "conferencePaper",
  "dataset",
  "dictionaryEntry",
  "document",
  "email",
  "encyclopediaArticle",
  "film",
  "forumPost",
  "hearing",
  "instantMessage",
  "interview",
  "journalArticle",
  "letter",
  "magazineArticle",
  "manuscript",
  "map",
  "newspaperArticle",
  "note",
  "patent",
  "podcast",
  "preprint",
  "presentation",
  "radioBroadcast",
  "report",
  "standard",
  "statute",
  "thesis",
  "tvBroadcast",
  "videoRecording",
  "webpage",
] as const;

const itemTypes = itemTypeNames.map((itemType) => [
  itemType,
  labelFromCamelCase(itemType),
]) as Array<readonly [string, string]>;

const itemFieldNames = [
  "DOI",
  "ISBN",
  "ISSN",
  "PMCID",
  "PMID",
  "abstractNote",
  "accessDate",
  "applicationNumber",
  "archive",
  "archiveID",
  "archiveLocation",
  "artworkMedium",
  "artworkSize",
  "assignee",
  "audioFileType",
  "audioRecordingFormat",
  "billNumber",
  "blogTitle",
  "bookTitle",
  "callNumber",
  "caseName",
  "citationKey",
  "code",
  "codeNumber",
  "codePages",
  "codeVolume",
  "committee",
  "company",
  "conferenceName",
  "country",
  "court",
  "date",
  "dateDecided",
  "dateEnacted",
  "dictionaryTitle",
  "distributor",
  "docketNumber",
  "documentNumber",
  "edition",
  "encyclopediaTitle",
  "episodeNumber",
  "eventPlace",
  "extra",
  "filingDate",
  "firstPage",
  "format",
  "forumTitle",
  "genre",
  "history",
  "identifier",
  "institution",
  "interviewMedium",
  "issue",
  "issueDate",
  "issuingAuthority",
  "journalAbbreviation",
  "label",
  "language",
  "legalStatus",
  "legislativeBody",
  "letterType",
  "libraryCatalog",
  "manuscriptType",
  "mapType",
  "meetingName",
  "nameOfAct",
  "network",
  "numPages",
  "number",
  "numberOfVolumes",
  "organization",
  "originalDate",
  "originalPlace",
  "originalPublisher",
  "pages",
  "partNumber",
  "partTitle",
  "patentNumber",
  "place",
  "postType",
  "presentationType",
  "priorityDate",
  "priorityNumbers",
  "proceedingsTitle",
  "programTitle",
  "programmingLanguage",
  "publicLawNumber",
  "publicationTitle",
  "publisher",
  "references",
  "reportNumber",
  "reportType",
  "reporter",
  "reporterVolume",
  "repository",
  "repositoryLocation",
  "rights",
  "runningTime",
  "scale",
  "section",
  "series",
  "seriesNumber",
  "seriesText",
  "seriesTitle",
  "session",
  "sessionTitle",
  "shortTitle",
  "status",
  "studio",
  "subject",
  "system",
  "thesisType",
  "title",
  "type",
  "university",
  "url",
  "versionNumber",
  "videoRecordingFormat",
  "volume",
  "websiteTitle",
  "websiteType",
] as const;

const itemFields = itemFieldNames.map((field) => [
  field,
  labelFromCamelCase(field),
]) as Array<readonly [string, string]>;

const itemTypeFields: Record<string, string[]> = {
  annotation: [],
  artwork: [
    "title",
    "abstractNote",
    "artworkMedium",
    "artworkSize",
    "date",
    "eventPlace",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  attachment: ["title", "url", "accessDate"],
  audioRecording: [
    "title",
    "abstractNote",
    "audioRecordingFormat",
    "seriesTitle",
    "volume",
    "numberOfVolumes",
    "label",
    "place",
    "date",
    "runningTime",
    "ISBN",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  bill: [
    "title",
    "abstractNote",
    "billNumber",
    "code",
    "codeVolume",
    "section",
    "codePages",
    "legislativeBody",
    "session",
    "history",
    "date",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  blogPost: [
    "title",
    "abstractNote",
    "blogTitle",
    "websiteType",
    "date",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "ISSN",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  book: [
    "title",
    "abstractNote",
    "series",
    "seriesNumber",
    "volume",
    "numberOfVolumes",
    "edition",
    "date",
    "publisher",
    "place",
    "originalDate",
    "originalPublisher",
    "originalPlace",
    "format",
    "numPages",
    "ISBN",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "ISSN",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  bookSection: [
    "title",
    "abstractNote",
    "bookTitle",
    "series",
    "seriesNumber",
    "volume",
    "numberOfVolumes",
    "edition",
    "date",
    "publisher",
    "place",
    "originalDate",
    "originalPublisher",
    "originalPlace",
    "format",
    "pages",
    "ISBN",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "ISSN",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  case: [
    "caseName",
    "abstractNote",
    "court",
    "dateDecided",
    "docketNumber",
    "reporter",
    "reporterVolume",
    "firstPage",
    "history",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  computerProgram: [
    "title",
    "abstractNote",
    "seriesTitle",
    "versionNumber",
    "date",
    "system",
    "company",
    "place",
    "programmingLanguage",
    "rights",
    "citationKey",
    "url",
    "accessDate",
    "DOI",
    "ISBN",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "shortTitle",
    "extra",
  ],
  conferencePaper: [
    "title",
    "abstractNote",
    "proceedingsTitle",
    "conferenceName",
    "publisher",
    "place",
    "date",
    "eventPlace",
    "volume",
    "issue",
    "numberOfVolumes",
    "pages",
    "series",
    "seriesNumber",
    "DOI",
    "ISBN",
    "citationKey",
    "url",
    "accessDate",
    "ISSN",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  dataset: [
    "title",
    "abstractNote",
    "identifier",
    "type",
    "versionNumber",
    "date",
    "repository",
    "repositoryLocation",
    "format",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  dictionaryEntry: [
    "title",
    "abstractNote",
    "dictionaryTitle",
    "series",
    "seriesNumber",
    "volume",
    "numberOfVolumes",
    "edition",
    "date",
    "publisher",
    "place",
    "pages",
    "ISBN",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  document: [
    "title",
    "abstractNote",
    "type",
    "date",
    "publisher",
    "place",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  email: [
    "subject",
    "abstractNote",
    "date",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  encyclopediaArticle: [
    "title",
    "abstractNote",
    "encyclopediaTitle",
    "series",
    "seriesNumber",
    "volume",
    "numberOfVolumes",
    "edition",
    "date",
    "publisher",
    "place",
    "pages",
    "ISBN",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  film: [
    "title",
    "abstractNote",
    "distributor",
    "place",
    "date",
    "genre",
    "videoRecordingFormat",
    "runningTime",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  forumPost: [
    "title",
    "abstractNote",
    "forumTitle",
    "postType",
    "date",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  hearing: [
    "title",
    "abstractNote",
    "committee",
    "publisher",
    "numberOfVolumes",
    "documentNumber",
    "pages",
    "legislativeBody",
    "session",
    "history",
    "date",
    "place",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  instantMessage: [
    "title",
    "abstractNote",
    "date",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  interview: [
    "title",
    "abstractNote",
    "interviewMedium",
    "date",
    "publisher",
    "place",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  journalArticle: [
    "title",
    "abstractNote",
    "publicationTitle",
    "publisher",
    "place",
    "date",
    "volume",
    "issue",
    "section",
    "partNumber",
    "partTitle",
    "pages",
    "series",
    "seriesTitle",
    "seriesText",
    "journalAbbreviation",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "PMID",
    "PMCID",
    "ISSN",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  letter: [
    "title",
    "abstractNote",
    "letterType",
    "date",
    "eventPlace",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  magazineArticle: [
    "title",
    "abstractNote",
    "publicationTitle",
    "publisher",
    "place",
    "date",
    "volume",
    "issue",
    "pages",
    "ISSN",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  manuscript: [
    "title",
    "abstractNote",
    "manuscriptType",
    "institution",
    "place",
    "date",
    "numPages",
    "number",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  map: [
    "title",
    "abstractNote",
    "mapType",
    "scale",
    "seriesTitle",
    "edition",
    "publisher",
    "place",
    "date",
    "DOI",
    "ISBN",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  newspaperArticle: [
    "title",
    "abstractNote",
    "publicationTitle",
    "publisher",
    "place",
    "date",
    "volume",
    "issue",
    "edition",
    "section",
    "pages",
    "ISSN",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  note: ["note"],
  patent: [
    "title",
    "abstractNote",
    "place",
    "country",
    "assignee",
    "issuingAuthority",
    "patentNumber",
    "filingDate",
    "pages",
    "applicationNumber",
    "priorityNumbers",
    "issueDate",
    "priorityDate",
    "references",
    "legalStatus",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  podcast: [
    "title",
    "abstractNote",
    "seriesTitle",
    "episodeNumber",
    "audioFileType",
    "date",
    "publisher",
    "place",
    "runningTime",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  preprint: [
    "title",
    "abstractNote",
    "genre",
    "repository",
    "archiveID",
    "place",
    "date",
    "series",
    "seriesNumber",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  presentation: [
    "title",
    "abstractNote",
    "presentationType",
    "date",
    "meetingName",
    "place",
    "series",
    "sessionTitle",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  radioBroadcast: [
    "title",
    "abstractNote",
    "programTitle",
    "episodeNumber",
    "audioRecordingFormat",
    "network",
    "place",
    "date",
    "runningTime",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  report: [
    "title",
    "abstractNote",
    "reportNumber",
    "reportType",
    "institution",
    "place",
    "date",
    "seriesTitle",
    "seriesNumber",
    "pages",
    "DOI",
    "ISBN",
    "citationKey",
    "url",
    "accessDate",
    "ISSN",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  standard: [
    "title",
    "abstractNote",
    "organization",
    "committee",
    "type",
    "number",
    "versionNumber",
    "edition",
    "status",
    "date",
    "publisher",
    "place",
    "partNumber",
    "partTitle",
    "ISBN",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "numPages",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  statute: [
    "nameOfAct",
    "abstractNote",
    "code",
    "codeNumber",
    "publicLawNumber",
    "dateEnacted",
    "pages",
    "section",
    "session",
    "history",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
  thesis: [
    "title",
    "abstractNote",
    "thesisType",
    "university",
    "place",
    "date",
    "series",
    "seriesNumber",
    "numPages",
    "DOI",
    "ISBN",
    "citationKey",
    "url",
    "accessDate",
    "ISSN",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  tvBroadcast: [
    "title",
    "abstractNote",
    "programTitle",
    "episodeNumber",
    "videoRecordingFormat",
    "network",
    "place",
    "date",
    "runningTime",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  videoRecording: [
    "title",
    "abstractNote",
    "videoRecordingFormat",
    "seriesTitle",
    "volume",
    "numberOfVolumes",
    "studio",
    "place",
    "date",
    "runningTime",
    "ISBN",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra",
  ],
  webpage: [
    "title",
    "abstractNote",
    "websiteTitle",
    "websiteType",
    "date",
    "publisher",
    "place",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "shortTitle",
    "language",
    "rights",
    "extra",
  ],
};

const creatorTypes = [
  ["artist", "Artist"],
  ["attorneyAgent", "Attorney/Agent"],
  ["author", "Author"],
  ["bookAuthor", "Book Author"],
  ["cartographer", "Cartographer"],
  ["castMember", "Cast Member"],
  ["chair", "Chair"],
  ["commenter", "Commenter"],
  ["composer", "Composer"],
  ["contributor", "Contributor"],
  ["cosponsor", "Cosponsor"],
  ["counsel", "Counsel"],
  ["creator", "Creator"],
  ["director", "Director"],
  ["editor", "Editor"],
  ["executiveProducer", "Executive Producer"],
  ["guest", "Guest"],
  ["host", "Host"],
  ["interviewee", "Interviewee"],
  ["interviewer", "Interviewer"],
  ["inventor", "Inventor"],
  ["narrator", "Narrator"],
  ["organizer", "Organizer"],
  ["originalCreator", "Original Creator"],
  ["performer", "Performer"],
  ["podcaster", "Podcaster"],
  ["presenter", "Presenter"],
  ["producer", "Producer"],
  ["programmer", "Programmer"],
  ["recipient", "Recipient"],
  ["reviewedAuthor", "Reviewed Author"],
  ["scriptwriter", "Scriptwriter"],
  ["seriesCreator", "Series Creator"],
  ["seriesEditor", "Series Editor"],
  ["sponsor", "Sponsor"],
  ["translator", "Translator"],
  ["wordsBy", "Words By"],
] as const;

const creatorTypeLabels = new Map<string, string>(creatorTypes);

const creatorTypeEntry = (creatorType: string, primary = false) => ({
  creatorType,
  localized:
    creatorTypeLabels.get(creatorType) ?? labelFromCamelCase(creatorType),
  ...(primary ? { primary: true } : {}),
});

const itemTypeCreatorTypes: Record<
  string,
  Array<{ creatorType: string; localized: string; primary?: boolean }>
> = {
  artwork: [creatorTypeEntry("artist", true), creatorTypeEntry("contributor")],
  attachment: [],
  audioRecording: [
    creatorTypeEntry("performer", true),
    creatorTypeEntry("originalCreator"),
    creatorTypeEntry("composer"),
    creatorTypeEntry("wordsBy"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("contributor"),
  ],
  bill: [
    creatorTypeEntry("sponsor", true),
    creatorTypeEntry("cosponsor"),
    creatorTypeEntry("contributor"),
  ],
  blogPost: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("translator"),
    creatorTypeEntry("commenter"),
    creatorTypeEntry("contributor"),
  ],
  book: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("editor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("seriesEditor"),
  ],
  bookSection: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("editor"),
    creatorTypeEntry("bookAuthor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("seriesEditor"),
  ],
  case: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("counsel"),
    creatorTypeEntry("contributor"),
  ],
  computerProgram: [
    creatorTypeEntry("programmer", true),
    creatorTypeEntry("contributor"),
  ],
  conferencePaper: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("editor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("seriesEditor"),
  ],
  dataset: [creatorTypeEntry("author", true), creatorTypeEntry("contributor")],
  dictionaryEntry: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("editor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("seriesEditor"),
  ],
  document: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("editor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("reviewedAuthor"),
  ],
  email: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("translator"),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("recipient"),
  ],
  encyclopediaArticle: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("editor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("seriesEditor"),
  ],
  film: [
    creatorTypeEntry("director", true),
    creatorTypeEntry("producer"),
    creatorTypeEntry("scriptwriter"),
    creatorTypeEntry("castMember"),
    creatorTypeEntry("host"),
    creatorTypeEntry("guest"),
    creatorTypeEntry("narrator"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("contributor"),
  ],
  forumPost: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
  ],
  hearing: [creatorTypeEntry("contributor", true)],
  instantMessage: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("recipient"),
  ],
  interview: [
    creatorTypeEntry("interviewee", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("interviewer"),
    creatorTypeEntry("translator"),
  ],
  journalArticle: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("editor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("reviewedAuthor"),
  ],
  letter: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("recipient"),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("translator"),
  ],
  magazineArticle: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("reviewedAuthor"),
  ],
  manuscript: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("translator"),
  ],
  map: [
    creatorTypeEntry("cartographer", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("seriesEditor"),
  ],
  newspaperArticle: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("reviewedAuthor"),
  ],
  note: [],
  patent: [
    creatorTypeEntry("inventor", true),
    creatorTypeEntry("attorneyAgent"),
    creatorTypeEntry("contributor"),
  ],
  podcast: [
    creatorTypeEntry("podcaster", true),
    creatorTypeEntry("guest"),
    creatorTypeEntry("producer"),
    creatorTypeEntry("executiveProducer"),
    creatorTypeEntry("seriesCreator"),
    creatorTypeEntry("director"),
    creatorTypeEntry("scriptwriter"),
    creatorTypeEntry("castMember"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("contributor"),
  ],
  preprint: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("editor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("reviewedAuthor"),
  ],
  presentation: [
    creatorTypeEntry("presenter", true),
    creatorTypeEntry("chair"),
    creatorTypeEntry("organizer"),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("translator"),
  ],
  radioBroadcast: [
    creatorTypeEntry("creator", true),
    creatorTypeEntry("host"),
    creatorTypeEntry("guest"),
    creatorTypeEntry("producer"),
    creatorTypeEntry("executiveProducer"),
    creatorTypeEntry("seriesCreator"),
    creatorTypeEntry("director"),
    creatorTypeEntry("scriptwriter"),
    creatorTypeEntry("castMember"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("contributor"),
  ],
  report: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("editor"),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("seriesEditor"),
  ],
  standard: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("editor"),
    creatorTypeEntry("contributor"),
  ],
  statute: [creatorTypeEntry("author", true), creatorTypeEntry("contributor")],
  thesis: [creatorTypeEntry("author", true), creatorTypeEntry("contributor")],
  tvBroadcast: [
    creatorTypeEntry("director", true),
    creatorTypeEntry("producer"),
    creatorTypeEntry("executiveProducer"),
    creatorTypeEntry("seriesCreator"),
    creatorTypeEntry("scriptwriter"),
    creatorTypeEntry("castMember"),
    creatorTypeEntry("host"),
    creatorTypeEntry("guest"),
    creatorTypeEntry("narrator"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("contributor"),
  ],
  videoRecording: [
    creatorTypeEntry("creator", true),
    creatorTypeEntry("director"),
    creatorTypeEntry("producer"),
    creatorTypeEntry("scriptwriter"),
    creatorTypeEntry("executiveProducer"),
    creatorTypeEntry("castMember"),
    creatorTypeEntry("host"),
    creatorTypeEntry("guest"),
    creatorTypeEntry("narrator"),
    creatorTypeEntry("translator"),
    creatorTypeEntry("contributor"),
  ],
  webpage: [
    creatorTypeEntry("author", true),
    creatorTypeEntry("contributor"),
    creatorTypeEntry("translator"),
  ],
};

export const validItemTypes = new Set(itemTypes.map(([itemType]) => itemType));
export const validCreatorTypes: Set<string> = new Set(
  creatorTypes.map(([creatorType]) => creatorType)
);
export const validAttachmentLinkModes = new Set([
  "embedded_image",
  "imported_file",
  "imported_url",
  "linked_file",
  "linked_url",
]);
export const validAnnotationTypes = new Set([
  "highlight",
  "image",
  "ink",
  "note",
  "text",
  "underline",
]);

export const getItemTypes = (locale = "en-US") => {
  const localized = itemTypeLocalizations[locale] ?? {};

  return itemTypes.map(([itemType, defaultLabel]) => ({
    itemType,
    localized: localized[itemType] ?? defaultLabel,
  }));
};

export const getItemFields = () =>
  itemFields.map(([field, localized]) => ({ field, localized }));

export const getItemTypeFields = (itemType: string) => {
  const fields = itemTypeFields[itemType];
  if (!fields) {
    return null;
  }

  const fieldLabels = new Map(
    itemFields.map(([field, localized]) => [field, localized])
  );
  return fields.map((field) => ({
    field,
    localized: fieldLabels.get(field) ?? field,
  }));
};

export const getItemTypeCreatorTypes = (itemType: string) =>
  itemTypeCreatorTypes[itemType] ?? [];

export const getCreatorFields = () => [
  { field: "firstName", localized: "First Name" },
  { field: "lastName", localized: "Last Name" },
  { field: "name", localized: "Name" },
];
