interface EphemeralBindings {
  BOOTSTRAP_TOKEN?: string;
  COMPATIBILITY_TEST_ADMIN_TOKEN?: string;
  COMPATIBILITY_TEST_API_KEY?: string;
  DEPLOYMENT_MODE: "compatibility-test" | "production";
  RECOVERY_TOKEN?: string;
  TEST_MIGRATIONS?: unknown;
  TTS_TEST_KEY?: string;
}

// `Env` is generated by `wrangler types` from wrangler.jsonc. The supplemental
// values are intentionally ephemeral: setup/recovery secrets are installed only
// for the duration of a CLI operation, while compatibility bindings exist only
// in the isolated Workers Vitest/official-oracle environment.
export type Bindings = Omit<Env, "DEPLOYMENT_MODE"> & EphemeralBindings;
